# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: l_arm
  joint_model_group_pose: l_arm_stow
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - l_ur5_arm_shoulder_pan_joint
    - l_ur5_arm_shoulder_lift_joint
    - l_ur5_arm_elbow_joint
    - l_ur5_arm_wrist_1_joint
    - l_ur5_arm_wrist_2_joint
    - l_ur5_arm_wrist_3_joint
    - r_ur5_arm_shoulder_pan_joint
    - r_ur5_arm_shoulder_lift_joint
    - r_ur5_arm_elbow_joint
    - r_ur5_arm_wrist_1_joint
    - r_ur5_arm_wrist_2_joint
    - r_ur5_arm_wrist_3_joint
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: l_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - l_ur5_arm_shoulder_pan_joint
      - l_ur5_arm_shoulder_lift_joint
      - l_ur5_arm_elbow_joint
      - l_ur5_arm_wrist_1_joint
      - l_ur5_arm_wrist_2_joint
      - l_ur5_arm_wrist_3_joint
  - name: r_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r_ur5_arm_shoulder_pan_joint
      - r_ur5_arm_shoulder_lift_joint
      - r_ur5_arm_elbow_joint
      - r_ur5_arm_wrist_1_joint
      - r_ur5_arm_wrist_2_joint
      - r_ur5_arm_wrist_3_joint